### ISSUE TITLE
No Damage with Bow and Trident (Ranged) when player.collision:false 

### ISSUE THREAD

**Issue by TerraPrimal** [Eredrim/pvparena#10]
Greetings,

It seems I am unable to damage the enemy team with a bow or Trident when thrown. There are no issues with melee or when not actively in an area.

I have removed any other software that could be conflicting (not a normal server using vanilla damage etc) and I am able to replicate the issue.
I have added below PA/Server version, arena and spigot config as well as a screenshot of plugins that were active within testing time.

Spigot: This server is running CraftBukkit version git-Spigot-1a3504a-dfa7583 (MC: 1.13.2) (Implementing API version 1.13.2-R0.1-SNAPSHOT) (FINAL BUILD)
PA: v1.13.9.301
PA Config: https://pastebin.com/2sCUtqu6
Plugins: https://i.gyazo.com/9b48bf52fbde1a20af3d53037235b76b.png
Example: https://i.gyazo.com/e3c910f23f0cb63f4fcc182a514ca7a1.gif

Seems that having player.collision:false causes this issue (tested it before submit), ill keep it here incase you can fix it.

**Comment by Eredrim** [comment]
Hello,
the collision parameter disables collisions with all kind of entities (included arrows and tridents). So without collision, projectiles can't make damage.
Therefore it's not a bug. I looked for if I could just disable collisions with other players, but the Spigot API seems not implement it. 
The only way to make that is patching spigot with plugins like this : https://www.spigotmc.org/resources/no-collision-with-patch-only-spigot.26347/
