### ISSUE TITLE
teleport flag not working

### ISSUE THREAD

**Issue by thunderated** [Eredrim/pvparena#101]
/pa ctf !p ctfbattle TELEPORT
ctf is name of arena
ctfbattle is the region

but people cant still teleport in to the arena. theyre using /back, to get there

**Comment by Eredrim** [comment]
Hello,
the aim of region protections is to manage allowed interactions between battlefield and arena contestants. People using /back are no longer arena players, so they are not concerned by these protections. If you want to prevent teleportation of external players from your battlefield, you should use BattlefiledGuard module which is designed for it. It teleports entering players to the "exit" spawn.
