### ISSUE TITLE
Negating pvparena.cmds permissions doesn't work

### ISSUE THREAD

**Issue by oskarkk** [Eredrim/pvparena#107]
Try denying e.g. `pvparena.cmds.join`, so add `-pvparena.cmds.join` to the permissions of some player/group. They will still be able to use `/pa join`. 

I think negating these permissions could be useful if you would want to have ops without every permission, or admins which could change only some properties of an arena.

**Comment by Eredrim** [comment]
Unfortunately, this can not be done because negative permissions can only be understood by permission plugins. In third party plugins (like PVPArena), we are only able to know if someone has a permission or not, negative permissions are not passed. So, the only possibility we have is to remove privileges granted to Ops and uniquely base our rights on bukkit permission system.

**Comment by oskarkk** [comment]
I don't understand. Plugins like Essentials, WorldEdit/Guard, Plan and other plugins running on my server handle negated permissions just fine. By default ops have all the perms, but you can take away op's perms by negating them, and if you give an user something like `plugin.perm.*` you can exclude specific permission like `-plugin.perm.subperm`.

**Comment by Eredrim** [comment]
I will check how they do it, I just hope they are not need Vault or another dependency. I try to let the plugin as independent as possible of servers ecosystems.

**Comment by Oruss7** [comment]
After some research, It's not vault but really the permission manager which handle this.
- Did you player is OP ?
- Did you have `pvparena.cmds.*` after of before the negative `-pvparena.cmds.join` ?

**Comment by oskarkk** [comment]
I've tested two cases.

1. Op: added `-pvparena.cmds.join` so `/pa join` should not work - it still worked. I had no other pvparena permissions.
2. Regular user: negated the same permission as above, without any other permissions, player still could join the arena.

**Comment by Oruss7** [comment]
Yeap, we have `"pvparena.user"` set everywhere and override children 😅

**Comment by oskarkk** [comment]
Okay, for regular users it's fixed, thanks.
![image](https://user-images.githubusercontent.com/16339637/120105294-9c63c880-c158-11eb-809d-30e115ad96fe.png)
When I negated `join` it's not even appearing in command completions, so it's as good as it can be.

But, for the case with ops, it still does not work. This is much less needed, but it's certainly doable and I can think of some scenarios when this could be handy.

**Comment by Oruss7** [comment]
Op without join command ? It's a very rare need indeed 😄

**Comment by oskarkk** [comment]
`join` command is just an example.

Checked right now and with negated `pvparena.admin` you can actually successfully negate `pvparena.cmds.join`, but I still think that `pvparena.admin` should be more like a parent than just override. In other plugins you can deny ops any command.

Imagine if you were to implement a region flag that would prevent people from entering that region if they aren't in a match. Then you could make permission like `pvparena.regionbypass` that would allow a player to enter every pvparena region, and ops would have this by default. Then, some ops wouldn't want to have this permission, as they would rather interact with regions by the rules of normal players. That's the case on my server with WorldGuard, where I (op) have `-worldguard.region.bypass.*` and then I interact with all regions as a normal player.

Overall, taking permissions away from ops is a nice fast way to test things and their behavior.

**Comment by Oruss7** [comment]
Perms system need a rework 😅

**Comment by oskarkk** [comment]
I think that everything works now, thanks @Oruss7!
