### ISSUE TITLE
/spawn not leaving the Arena game the player is in

### ISSUE THREAD

**Issue by n1msy** [Eredrim/pvparena#12]
Whenever you do /spawn, you keep your kit, and although you teleport to the spawn area, the plugin acts as if you are still in the game, and you have to manually type /pa leave

**Comment by Eredrim** [comment]
Hi,
I made some tests during last days and I didn't reproduce what you describe.
The things I can confirm : 
- You can use /spawn within an arena if you are OP or if you have the `pvparena.admin` or the `pvparena.create` permission
- If you didn't set any regions, you can go everywhere without leaving the game

Are these elements could help you ? If not, can you attach your arena config (directly in the ticket or using paste service like pastebin) ?

**Comment by n1msy** [comment]
> Hi,
> I made some tests during last days and I didn't reproduce what you describe.
> The things I can confirm :
> 
> * You can use /spawn within an arena if you are OP or if you have the `pvparena.admin` or the `pvparena.create` permission
> * If you didn't set any regions, you can go everywhere without leaving the game
> 
> Are these elements could help you ? If not, can you attach your arena config (directly in the ticket or using paste service like pastebin) ?

So what I mean is, whenever I do /spawn, i still keep my stuff from the gamemode and the plugin thinks I'm still in the gamemode

**Comment by phsikotic** [comment]
/spawn does not leave the arena for me either.  still have to use /pa leave 

Kind of a pain since players need to know this command -  not sure how else to do it

**Comment by Eredrim** [comment]
This is not a bug. The described behavior is completely normal. To leave an arena, players have to use `/pa leave` or disconnect.
