### ISSUE TITLE
Error title for CTF even when complete?

### ISSUE THREAD

**Issue by Creeper-Kingz** [Eredrim/pvparena#138]
I've set up a few FFA maps on my server with this plugin and it seems to be working great, but with CTF I can't work it out. We have created the arena as CTF, created the two teams, then the two team spawns and lounges, as well as setting the exit spawn and spectator spawn. We have also set the flag type as white_wool. (Can't seem to make it a banner?). But when its complete and we try to use either /pa (arenaname) join blue or /pa (arenaname) it shows the following error message.

ERROR: Spawn missing: 2/4x lounge

Any idea how to fix this? Thanks

**Comment by Eredrim** [comment]
Hello,

Can you post your arena config file please? (Here or on our discord server). I need it to understand what could be wrong with your arena.

**Comment by Eredrim** [comment]
Assuming I answered you on discord, I close this issue.
