### ISSUE TITLE
Equip heads in kit

### ISSUE THREAD

**Issue by GabrielChev** [Eredrim/pvparena#145]
Hello,
The kits don't auto equip the heads.
When we save a kit with the zombie head on our head slot that delete it when we load it.
If we have the head in inventory that doesn't auto equip it.
Is there a way to have it on head when we load the kit ?
Thanks a lot

**Comment by Eredrim** [comment]
Hello,
It is a bug. I fixed it in the latest dev build, you can download it from our discord server.
