### ISSUE TITLE
Arena with EventActions module does not load properly

### ISSUE THREAD

**Issue by farum12** [Eredrim/pvparena#149]
**Issue:**
As in the title - the arena with the EventActions module does not load properly. 
Without the EventActions module, the arena is properly loaded, is listed with /pa list.

Below's image with the log:

![image](https://user-images.githubusercontent.com/56656135/180668399-392d65af-9dca-477c-8c52-7628a7c62472.png)

**Version Info:**

- Server jar's tested: Purpur 1.19
- Client version: Java 1.19
- PVP Arena 1.15.2

**Comment by farum12** [comment]
I think this can be closed now, as my fix seems to be working properly :)

**Comment by Eredrim** [comment]
Correct. I always forgot to close issues affecting modules (I can't autoclose them with commit messages)
