### ISSUE TITLE
Spectate module doesn't launch gamemode change on player death

### ISSUE THREAD

**Issue by farum12** [Eredrim/pvparena#152]
As the title suggests - after death (per config), the player is teleported to the spectator spawn point, however, he's not granted with Spectator gamemode. 
If the player leaves the arena (/pa leave), and joins the spectators - he joins in the Spectator gamemode. 

This has been confirmed by @Eredrim on Discord, I'm reporting for tracking purposes.

**Comment by Eredrim** [comment]
Fixed in 2.0 dev preview.
