### ISSUE TITLE
EventActions not working on 1.19

### ISSUE THREAD

**Issue by cyanice** [Eredrim/pvparena#153]
Having issues with EventActions, here's the error message:

https://hastebin.com/ducofuzomo.apache

This is the code that I added manually from the arena:

event:
  join:
  - 'cmd<=>mycmd-variables add bctcount 1'
  - 'msg<=>Welcome to %arena%!'

**Comment by Eredrim** [comment]
Already solved in #149. Please download latest dev build to get the fix.

**Comment by Eredrim** [comment]
I'll try to investigate with you on discord until we're sure this is a new distinct issue. If so, I'll repoen it.

**Comment by cyanice** [comment]
Thank you so much, and sorry for the trouble.
