### ISSUE TITLE
Update to 1.19

### ISSUE THREAD

**Issue by BobtheBob123456** [Eredrim/pvparena#154]
Hi Guys,
The reason I am contacting you guys because I'm wondering whether or not this plugin already supports 1.19, and if not, when will it update.

Thanks

**Comment by Eredrim** [comment]
Hi,
1.19 is supported. Following to your message, I updated the plugin page on SpigotMC.org.
If you need to use EventActions mod, please download the latest dev build of the modules pack on our discord.
