### ISSUE TITLE
players lose inventory after death

### ISSUE THREAD

**Issue by WarWolf-1** [Eredrim/pvparena#155]
Players lose everything and nothing is dropped when they die.
the game rule is set to drop items on death and arena settings disable item drops. the end result is that players lose everything and nothing gets dropped.

**Comment by Eredrim** [comment]
Hello,
I don't really understand what is your problem. 
* If you want players drop their inventory, just set `player.dropsInventory` to true. 
* If you want players keep their inventory before death, keep the setting to false and set `items.keepAllOnRespawn` to true. 
* If you want players get a new inventory on respawn (based on their class), keep `player.dropsInventory` and `items.keepAllOnRespawn` to false, then set `player.refillInventory` to true. This is the default behavior

The description of all arena settings can be found in the documentation, chapter "configuration".

**Comment by Eredrim** [comment]
No answer
