### ISSUE TITLE
Expand joinInBattle settings to only allow players to rejoin the same team if previously played.

### ISSUE THREAD

**Issue by mibby** [Eredrim/pvparena#16]
I use the ``joinInBattle: true`` setting for a few of my arenas. I would like to continue using this setting and let players join if they missed the initial queue, however it is being abused to switch teams in the middle or end of the game to stack to the winning side for rewards.

Would it be possible to allow for new people to join the arena and expand the logic of rejoining to the same team they were playing previously?

**Comment by Eredrim** [comment]
Yes it may possible to force player to rejoin the same team and I think it's a great feature. I think I would combine with the "onlyifhasplayed" parameters explained here : https://github.com/Eredrim/pvparena/issues/17#issuecomment-515000386

**Comment by mibby** [comment]
Forcing the same team for people who have left would definitely be appreciated and nice to have. :) I had to disable the join-in-progress feature for now due to players abusing.

**Comment by Eredrim** [comment]
In 2.0 dev preview, joinInBattle handles team number checks and there's a new feature that allows to rejoin the arena in case of disconnection.
