### ISSUE TITLE
betterclasses effects not being given to classes

### ISSUE THREAD

**Issue by ItzEnderArkail** [Eredrim/pvparena#167]
for some reason effects aren't still applied to classes when the fight starts

**How to Reproduce**
1. give any effect to a class(example INVISIBILITY 0)
2. join the arena and choose that class
3. start the arena or wait for it to start and there you have it, the effect ain't given

**Config information**
- Server software and version: purpur 1.18.2
- Java Version: 17.0.10
- PVPArena version: 2.0.0 snapshot b43
- the module being affected is betterclasses

**Comment by Eredrim** [comment]
Hi,
The power of the effect should be greater than 0 to get the effect. For instance, if you want to add the effect INVISIBILITY, you should add INVISIBILITY 1 (or just don't specify the value). For SLOW II, type SLOW 2, etc.
There was a bug in previous builds that automatically added 1 to effect value in previous version than yesterday one.

**Comment by ItzEnderArkail** [comment]
> Hi, The power of the effect should be greater than 0 to get the effect. For instance, if you want to add the effect INVISIBILITY, you should add INVISIBILITY 1 (or just don't specify the value). For SLOW II, type SLOW 2, etc. There was a bug in previous builds that automatically added 1 to effect value in previous version than yesterday one.

for the power yeah i tried with 1, 10 and 100 and the effect just disappears instantly after the fight starts

**Comment by Eredrim** [comment]
Hello,
I tried to reproduce and I can't get it. As of me, players keep effect on start, on respawn and even if they change their class ingame, the new class effect replaces the former one.
So, the logical conclusion is you have a conflict. Probably with a permission or a region plugin, or maybe with another PVPArena module if you enabled several ones. You should check what is enabled and try to disable other PVPArena modules.

**Comment by ItzEnderArkail** [comment]
> Hello, I tried to reproduce and I can't get it. As of me, players keep effect on start, on respawn and even if they change their class ingame, the new class effect replaces the former one. So, the logical conclusion is you have a conflict. Probably with a permission or a region plugin, or maybe with another PVPArena module if you enabled several ones. You should check what is enabled and try to disable other PVPArena modules.

i tried disabling all modules and creating a testarena to make sure there wasn't any conflict and still the effects don't work for some reason (the video is showing the Tank class(default class on arena creation) with the effect slow 1 given)


https://github.com/Eredrim/pvparena/assets/29746640/1842207e-8f12-4c97-ad6c-9675ed7c9be8

**Comment by Eredrim** [comment]
Hi!
Force starting is not the good way to start an arena (I think I'll remove this feature). Use `/pa ready` with at least two players and everything will work.

**Comment by ItzEnderArkail** [comment]
> Hi! Force starting is not the good way to start an arena (I think I'll remove this feature). Use `/pa ready` with at least two players and everything will work.

force starting has never failed to me when testing arenas, here's with 2 players, same result

https://github.com/Eredrim/pvparena/assets/29746640/19148194-c71e-4107-81c4-4e3fadc4002c

**Comment by ItzEnderArkail** [comment]
i even tested it on a empty server and still doesn't work.

**Comment by Eredrim** [comment]
Fixed!
The issue was specific to version 1.18 and before. PotionEffect API doesn't support infinite value (-1) before Bukkit 1.19.
The patched version was tested on both 1.18 and 1.20 versions.
