### ISSUE TITLE
Integrate Arena Rounds into the plugin

### ISSUE THREAD

**Issue by ItzEnderArkail** [Eredrim/pvparena#169]
i think it would be great if we had it in the plugin itself with the option being `uses.rounds` and requiring a number(by default 1), another option being `uses.roundsrandomizeteams` requiring true/false(it will randomize the teams in each round) the round and total rounds should be shown in the scoreboard too

**Comment by Eredrim** [comment]
Rounds are a feature that has been removed from 2.0 version and that will not be added again due to its complexity. This setting is just a piece of configuration that has not been removed.

**Comment by Eredrim** [comment]
After checking, this setting has already been removed. I will removed unused translation parts.
