### ISSUE TITLE
Expand joinInBattle settings to only allow players to join if the teams are uneven.

### ISSUE THREAD

**Issue by mibby** [Eredrim/pvparena#17]
Would it be possible to expand the logic of joinInBattle so you can only join an arena after it has started if the teams are uneven due to someone leaving? This way you could fill the ranks back up due to disconnects and avoid team switchers.

**Comment by Eredrim** [comment]
I don't think it's a good idea because if you already have uneven teams and someone quits then they can't re-join the game.
I rather suggest you to use the "onlyifhasplayed" setting to be sure a player who joins an arena has formely left it.

**Comment by mibby** [comment]
What if they quit and have no intentions of re-joining the game but you want to fill the team count back up with a random someone else so it is even and fair again?

**Comment by Eredrim** [comment]
In 2.0 dev preview, joinInBattle handles team number checks and there's a new feature that allows to rejoin the arena in case of disconnection.
