### ISSUE TITLE
Recompensas 

### ISSUE THREAD

**Issue by MRHUGO247** [Eredrim/pvparena#172]
**Describe the bug**
No es un problema como tal, es que no se como poner recompensas.

**Reproduction steps**
Lo que hago es que en el apartado de config de mi arena, en las recompensas pongo el ítem y seguido un numero para indicar la cantidad que quiero, no se si lo estoy haciendo bien. ¿Alguien podría ayudarme? 

**Additional elements**
Lo estoy haciendo en aternos. 

**Config information**
- Server software and version: 1.21 y uso Spigot 
- Java Version: 
- PVPArena version: [pvparena-1.15.3.jar]
-

**Comment by Eredrim** [comment]
Answered on discord.
https://discord.com/channels/268488399994880010/776536593766416416/1261097460151877723
