### ISSUE TITLE
RespawnRelay - Infect arena ends when all infected are "respawning"

### ISSUE THREAD

**Issue by aaluzzi** [Eredrim/pvparena#19]
I've got an infect arena using RespawnRelay where each infected has multiple lives. 

Despite the infected having lives left, the game will end when every infected player has to "respawn" at the same time. The message "The infected have been killed" displays to players, and the console spits out `[WARN] [PVP Arena] player null!`. If there's at least one infected that stays alive while others are respawning, the game functions normally. They are only safe to die when another infected has respawned.

This issue is easily reproducible with the one infected player at the start of the game. Kill that player before they can infect anyone. They'll die and it'll display their lives remaining, but then the game will end.

**Comment by Eredrim** [comment]
There are several bugs in respawnRelay, a big work is needed on this module. A fix is planned but it may take some time due to my other priorities (personal and for the plugin).

**Comment by Eredrim** [comment]
Fixed in 2.0
