### ISSUE TITLE
Can't make any spawnname besides spawn, lounge, and spectator

### ISSUE THREAD

**Issue by M1staAwesome** [Eredrim/pvparena#20]
Using latest dev pvparena modules and latest pvparena dev build, but if I try setting a spawnname that's anything besides `spawn`, `lounge`, and `spectator`, it doesn't work. Trying this on a deathmatch map.

**Comment by Eredrim** [comment]
Hello, 
Does your arena work with teams or in "free for all" mode ? When your create spawns your just need to set one spawn by team, one lounge by team, a spectator zone and an exit. If your are in a free for all arena, you have just one lounge and you can create as much spawns as you want.
So I don't understand what you try to do.

**Comment by M1staAwesome** [comment]
It's supposed to be a deathmatch, which I'm assuming would just be a 1v1, with one person on one team and the other person on the other team? What I'm confused on is how I set one spawn by team, because I can't have any spawn name except for the word `spawn`, so I don't know how I can differentiate between teams.

**Comment by Eredrim** [comment]
PVP Arena works with a goal system. You can create different kind of games with the same plugin. In the case you want to create a 1 vs 1 death match, you have two ways to create it : 
* The first one is to create a _teamDeathMatch_ and limit the number of players at one by team. In this case, you will need to set each team spawn by typing `/pa [arena] spawn teamnamespawn`. Default team names are "blue" and "red"
* The second is by using the _playerDeathMatch_ goal and limiting the number of players at two for the arena. In this case, players will spawn randomly and you can create as much spawn as you want with `/pa [arena] spawn spawnX` where X is a number.

To change the goal of the arena, just type `/pa [arena] goal goalName`. I suggest you to have a look [to the docs](https://github.com/Eredrim/pvparena/blob/master/readme.md), in particular the "creation", "commands" and "enhancements" parts.

If you need more informations, don't hesitate to ask me ;)

**Comment by M1staAwesome** [comment]
Alright that clears up things a lot more lol, thanks
