### ISSUE TITLE
specialjoin mod doesnt work

### ISSUE THREAD

**Issue by phsikotic** [Eredrim/pvparena#22]
unable to use the command to /pa (arena) setjoin

It give you the message "Setting join Block!"  
but no matter what you do, right or left click.. using wand, using stick... cant make a selection.  I'm trying on all the blocks it says works -  lever, button, sign.  

Typing the command again ends the selection

**Comment by phsikotic** [comment]
also -  is there any way to set up a sign to leave an arena when you're in the lobby? 

seems the only way to do it is if a player types out the command, and they have to specify the arena name if there is more than one.. That is a lot to ask from some players 

trying to use commandsigns,  the signs wont work after ive joined an arena unfortunately.

**Comment by Eredrim** [comment]
I will check the specialjoin problem. Concerning the way to leave an arena or a lobby, players just have to type `/pa leave` (without any arena name) to quit the game. This command can be written in a command block an used with redstone (pressure plate, button, etc).

**Comment by phsikotic** [comment]
thanks for the quick reply! 

I tried as you suggested with a command block but when players join the arena they are unable to use any buttons or levers..  They can use them again after leaving the arena

**Comment by Eredrim** [comment]
Just disable region protections to allow redstone usage. `/pa <arena> !p <region> redstone false`

You will find region docs here : https://github.com/Eredrim/pvparena/blob/master/doc/regions.md

**Comment by phsikotic** [comment]
Ah so there is one for commandblocks ok!  

i see REDSTONE listed on the region page you linked but..  not in game.  

[PVP Arena] RegionFlag REDSTONE unknown! Valid values: BREAK FIRE MOBS NATURE PAINTING PISTONE PLACE TNT TNTBREAK DROP INVENTORY PICKUP CRAFT TELEPORT

**Comment by Eredrim** [comment]
Hello !
Firstly I apologize for my so late answer. Effectively restone flag doesn't exist anymore. In order to allow player interactions in lounge, just create an arena region with type  `LOUNGE` for you lobby.
