### ISSUE TITLE
Joining message on version is 0.0.0

### ISSUE THREAD

**Issue by xSepticSidx** [Eredrim/pvparena#23]
I have version 1.14.0 installed however when I join I get a message telling me that it is version 0.0.0

I am on paper 1.14.4

**Comment by Eredrim** [comment]
It's a version detection bug. Download the [latest snapshot](https://ci.craftyn.com/job/PVP%20Arena/lastBuild/) or just disable the message in your general config file.

**Comment by xSepticSidx** [comment]
Hi, how do I disable the message please?
Thank you - Sid

**Comment by Eredrim** [comment]
Set `update.plugin` to false in your general config file, just like this : https://github.com/Eredrim/pvparena#update-checker
