### ISSUE TITLE
{loungeinteract: true} not working

### ISSUE THREAD

**Issue by leovah** [Eredrim/pvparena#27]
What steps will reproduce the problem?
1. Create arena
2. set  loungeinteract: true
3. join arena and attempt interactions with various items/blocks (for example, chests, buttons, etc..).

What type of arena are you using? (ctf? teams? free?)
Teams, specifically team deathmatch.

What is the expected output? What do you see instead?
Some sort of interaction with buttons, chests, barrels. Nothing happens.

What version of PVP Arena // CraftBukkit are you using? ("latest" will flag this as invalid!!)
1.14.0

What does "/pa version" print out? (screenshot or via console and copy from logfile)

https://pastebin.com/nWj4AKbu

Do you have an error log of what happened? (www.pastebin.com)
No error

Please post your arena arena yml(s). (www.pastebin.com)

https://pastebin.com/LEVXg9fm

Please provide any additional information below:
I am specifically trying to get commandsigns to work while in the arena, however as of now, it does not. I first thought this was an issue of the compatebility between the two different plugins, but then I noticed that the player is not able to interact with regular chests/barrels too.

**Comment by Eredrim** [comment]
Hello,

it's fixed in latest dev builds. However I suggest you creating a region with type `LOUNGE` for your lounge instead of use `loungeinterract`. It's less permissive for players and you can manage each protection as for battleground.
