### ISSUE TITLE
Fire keeps burning on BlockRestore

### ISSUE THREAD

**Issue by J-SHarper** [Eredrim/pvparena#28]
While all other blocks are restored through BlockRestore, flames are not extinguished, leaving the entire arena on fire.

**Comment by Eredrim** [comment]
Hello, it's a known behavior and not a bug. BlockRestore job's is only to restore blocks placed and destroyed by players. If you want to reset your arena completely (including fire), I suggest you to use [worldedit module](https://github.com/Eredrim/pvparena/blob/master/doc/mods/worldedit.md).

**Comment by J-SHarper** [comment]
Ah okay, thank you!
