### ISSUE TITLE
itemsonkill config setting not using new serializer.

### ISSUE THREAD

**Issue by mibby** [Eredrim/pvparena#3]
Compiled PVPArena as of commit https://github.com/Eredrim/pvparena/commit/3ef4b52fd1161c4d727562f4d1cf2efcedb68dd2

``itemsonkill`` config setting still seems to use the full itemstack output, not your new serializer.

Tested with ``/pa test set itemsonkill hand`` while holding an arrow (which didn't seem to set anything) and ``/pa test set itemsonkill inventory`` which set the arrow with the full inventory itemstack.

**Comment by Eredrim** [comment]
Please compile the latest version and tell me if it is corrected.

**Comment by mibby** [comment]
``/pa Chamber set itemsonkill inventory`` does work and is corrected to use the new serializer.

``/pa Chamber set itemsonkill hand`` does not work, I believe it's just outright broken.

**Comment by Eredrim** [comment]
Normally all is fixed. Please confirm in order to close the issue.

**Comment by mibby** [comment]
Confirmed fixed as of commit https://github.com/Eredrim/pvparena/commit/75555b959548a2665c90f7bf63ba20606ac88f72, thanks!
