### ISSUE TITLE
Questions respect rewards

### ISSUE THREAD

**Issue by celciusjj** [Eredrim/pvparena#30]
Can i make that with a command give money to my users? also I have this error when run in 1.15.2

>.... [20:38:54 WARN]: [PVP Arena] Task #416231 for pvparena v1.14.0 generated an exception
java.lang.ArithmeticException: null

**Comment by Eredrim** [comment]
Hello,

please take care to open a complete issue, precising your pvparena version, which mods and goals you use, what you try to do, what you get and when the error occurs.
