### ISSUE TITLE
CTF Arena Throwing Errors

### ISSUE THREAD

**Issue by J-SHarper** [Eredrim/pvparena#31]
My CTF arena threw these very angry errors for quite awhile:

https://pastebin.com/8qU2bnQS

I'm not sure whether anyone was actually playing in it, as I was not in the server at the time. I don't know enough to interpret the error.

**Comment by Eredrim** [comment]
Hello,

Can you precise your PVPArena version and share your arena config file please ? Otherwise, I can't do nothing with so little information.

**Comment by J-SHarper** [comment]
Yes!

![image](https://user-images.githubusercontent.com/6518001/81000671-9f38a080-8e14-11ea-95ce-537c42107717.png)

Here's the arena config:

https://pastebin.com/B7q0FpFH

**Comment by Eredrim** [comment]
Hello,

`exit` spawn is missing. Normally it is not mandatory but battlefieldguard module needs it. Just set it with `/pa <arena> spawn exit`.

**Comment by Eredrim** [comment]
Fixed in 1.15 snapshot
