### ISSUE TITLE
CheckPoint Goal Error

### ISSUE THREAD

**Issue by J-SHarper** [Eredrim/pvparena#32]
For the gamemode CheckPoint (https://github.com/Eredrim/pvparena/blob/master/doc/goals/checkpoints.md), I set up 10 checkpoints, one on each floor of a parkour tower. Players who reach the first checkpoint are able to stand on it and not move, and will automatically achieve the other checkpoints. See the gif below. 

Version: 
![image](https://user-images.githubusercontent.com/6518001/81002611-841b6000-8e17-11ea-90ad-36b666ead462.png)

Arena config: https://pastebin.com/kRrHgwuq

Problem illustrated: 
![Checkpoint](https://user-images.githubusercontent.com/6518001/81002661-a01f0180-8e17-11ea-96a4-7e2fe13c8897.gif)

**Comment by Eredrim** [comment]
Fixed in latest dev build. Can you confirm issue is resolved ?

**Comment by J-SHarper** [comment]
Can confirm this now works. Thank you!
