### ISSUE TITLE
Shutdown Error

### ISSUE THREAD

**Issue by J-SHarper** [Eredrim/pvparena#33]
Sorry to report so many errors, just posting them as I see them.

When PVPArena shuts down, it throws this error: https://pastebin.com/0iud5pSH

Version: 
![image](https://user-images.githubusercontent.com/6518001/81325190-04370500-9066-11ea-9d45-261b390e93c0.png)

**Comment by Eredrim** [comment]
Fixed in 1.15.0-Snapshot
