### ISSUE TITLE
[1.15] CTF issue

### ISSUE THREAD

**Issue by Eredrim** [Eredrim/pvparena#39]
_Opened by mibby_

Players are still not able to claim captured flags in CTF using the Flags goal. Maybe "touchdown" was in quotes for a reason in the source?

Upon testing, red team was able to grab blue team's flag at the start of the game. However blue's flag was white when the game started. After grabbing it and bringing it home, the flag returned and the white wool turned blue properly. Once the first claim was done, red was unable to grab the flag again. I think there may be an issue with returned flags not being able to be grabbed or turned in after the initial spawn. Such as if someone dies with the flag or makes a touchdown.

Config Example
https://paste.ubuntu.com/p/b3hJg2pZpn/

-----------------------------

Ah, yep, that's definitely the issue. Blue's flag turns white at game start but can be grabbed. It is light_blue wool on the player's head and can be turned in. Once the source flag block is returned, blue's flag block properly goes back to what it is defined as instead of white. However no one can claim or turn in the block if it's light_blue wool. If I set the wool to white with worldedit, it properly can be claimed or turned in at.

So the dev branch is setting one of the team's flag location colors improperly.

**Comment by Eredrim** [comment]
Fixed !
There was a problem with the code which check materials colors, it was not able to handle composed colors like "light_blue". You can test it with build #324

**Comment by mibby** [comment]
I have not heard any complaints since updating to dev 324. Seems to be fixed, thanks. :)
