### ISSUE TITLE
Jailed players in liberation are still able to hit opposing teammates if the jail is exposed or has half blocks. 

### ISSUE THREAD

**Issue by mibby** [Eredrim/pvparena#4]
RE: https://github.com/slipcor/pvparena/issues/345
Compiled as of commit https://github.com/Eredrim/pvparena/commit/3ef4b52fd1161c4d727562f4d1cf2efcedb68dd2

Shouldn't the damage event be cancelled if you are jailed (in dead state) in Liberation?

**Comment by Oruss7** [comment]
Can be fixed. I'm working on it.
