### ISSUE TITLE
Powerups not working

### ISSUE THREAD

**Issue by XMCaster** [Eredrim/pvparena#40]
PVP Arena version 1.15.0-SNAPSHOT-b323
Powerups version 1.14.1-SNAPSHOT
Server version: git-Paper-280 (MC: 1.15.2)

Arena config in attach.

Powerup "Heal" don't spawn at spawnpoint powerupX.
There is no errors in servver logs.

[CTFArena.txt](https://github.com/Eredrim/pvparena/files/4666956/CTFArena.txt)

**Comment by XMCaster** [comment]
Upd spigot to git-Paper-307 (MC: 1.15.2).

**Comment by Eredrim** [comment]
Fixed ! Documentation was unclear (like as usual), now powerups settings have to be set at the following path `modules.powerups.items`. Docs were updated (on 1.15 branch) and anyway all documentation will be rewritten soon.
