### ISSUE TITLE
Several Arenas now requiring exit spawns 

### ISSUE THREAD

**Issue by J-SHarper** [Eredrim/pvparena#42]
Several arenas, which before would simply deposit players to the spot where they joined from, now require exit spawns. These include Spleef and FFA arenas. 

![image](https://user-images.githubusercontent.com/6518001/82824879-25765e80-9e78-11ea-9955-515c56e8d65e.png)

Version: the latest snapshot (324)

**Comment by Eredrim** [comment]
That's completely normal and it only concerns your arena with BattlefieldGuard mod. This mod always needed an "exit" spawn but there was a bug that never ask user to set it. I fixed it in recent snapshots.

**Comment by J-SHarper** [comment]
Ohhhh right. 🤦‍♂️ So sorry, you did say that! Thanks
