### ISSUE TITLE
Duel arena requires more spawns than the maximum players allowed.

### ISSUE THREAD

**Issue by mibby** [Eredrim/pvparena#43]
PVPArena dev 324

Config Example
https://paste.ubuntu.com/p/VK7J5J8HdZ/

Arena seems to require more spawns available than the maximum player count to be able to join. I only allow 2 people to fight in my duel arena, however I'm forced to set additional spawns that overlap each other since it claims spawns are missing. 

i.e.
```
  spawn1: void,-1235,75,1256,269.9588317871094,0.8553600311279297
  spawn2: void,-1195,76,1259,89.9615478515625,0.11487597972154617
  spawn3: void,-1235,75,1256,269.9588317871094,0.8553600311279297
  spawn4: void,-1195,76,1259,89.9615478515625,0.11487597972154617
```

Assuming this is caused by using the ``smartspawn`` algorithm? If it requires an additional spawn above the number of maximum players for calculations. 

For reference, I use smart instead of quick spawning because I always want the dueling partner to spawn the furthest away from the alive player.

**Comment by Eredrim** [comment]
It's much simpler than that. Free for all arenas need at least 4 spawns. I think this choice was made to better randomize spawning.
So it's not a bug (good news for me 😋)

**Comment by mibby** [comment]
Ah, yep. I forgot about that. :) 

Would it make sense for the PlayerLives goal / FREE team to check the minimum and maximum players defined for spawns required instead of being a hard minimum limit? That way you could have less spawns for very small arenas. 

Alternatively, could just clone the PlayerLives goal and rename it to Dueling or something for just 1vs1 and 2 spawn minimum check. I don't know if anyone would have a FFA arena with just 3 spawns, but could be wrong.

**Comment by Eredrim** [comment]
I'm not in favor of creating a limit which may depend on another setting in the arena config file. Nevertheless I think it might be possible to set this limit to "2", normally the plugin can handle it but this kind of change would require a lot of tests. In any case code will be duplicated, I want to keep this plugin as clean as possible.

Otherwise, you can just duplicate the two first spawn points you created.

**Comment by mibby** [comment]
I'd be fine with the hard limit changed to 2 just so I don't have to have overlapping spawns.

I understand the initial reason for the hard limit and a change to check maximum players would just be more about safe guarding against not having enough spawns for the amount of people playing. But that should probably fall into being user setup error instead of the plugin's fault.
