### ISSUE TITLE
Colored nicknames in Tab menu after match with NametagEdit

### ISSUE THREAD

**Issue by XMCaster** [Eredrim/pvparena#44]
Hello!

I have a problem with colored nicks NametagEdit plugin.
After the match, nicknames turn white color.
Relog helping, but this is not a solve :(
I would like the colors of nicknames to be restored after the match

Thanks!

![nicknames](https://user-images.githubusercontent.com/65759760/83199220-38c84900-a15a-11ea-9332-7ffaa6ff0ce1.jpg)

**Comment by XMCaster** [comment]
Spigot version: git-Paper-307 (MC: 1.15.2).
PVP Arena version 1.15.0-SNAPSHOT-b323

**Comment by Eredrim** [comment]
Hi, try dev build [#326](https://ci.craftyn.com/job/PVP%20Arena/), normally this bug should be fixed. Related issue is #35

**Comment by XMCaster** [comment]
Hi, i tryed builds 326 and 327, but there is still an issue

**Comment by Eredrim** [comment]
Hello,
I made some tests with nametagEdit. In my case, plugin has some difficulties to correctly display custom tags in the tab menu even when PvPArena is not used. After checking of NametageEdit code, it seems their plugin works by sending packets and not with scoreboards. So, unlike I could say in my previous messages, it's not related to the scoreboard displaying issue.
So I would not able to do nothing except integrate this plugin specifically by calling their APIs, and that's not planned.

**Comment by Eredrim** [comment]
A (temporary) solution I can suggest you is using [eventactions module](https://github.com/Eredrim/pvparena/blob/master/doc/mods/eventactions.md) and call `/nte reload` command when someone wins the game (i.e. when arena ends).
