### ISSUE TITLE
how to fill chests with pre picked items before a duel

### ISSUE THREAD

**Issue by SimplyAlex08** [Eredrim/pvparena#45]
Please could you reply with instruction on how to do this.

**Comment by Eredrim** [comment]
Hello,

I suggest you to use the well-named module "chestfiller", you can find associated documentation here: https://github.com/Eredrim/pvparena/blob/master/doc/mods/chestfiller.md

In addition, even we are on the internet, I think your demand could be a little less directive in my opinion. Just try to begin with "hello", it's cheap and it always pleases 😉
