### ISSUE TITLE
NPCs (fake players) are showing up in PVPArena stats.

### ISSUE THREAD

**Issue by mibby** [Eredrim/pvparena#46]
Citizens2 dev 1982
PVPArena dev 328

Typing ``/pa stats damage`` after players have played in some arenas shows players who aren't actually participating in any of the arenas. Citizen NPCs are showing up in the output.

![link](https://i.imgur.com/vb3SxR9.png)

Would it be possible to filter out players who contain the meta NPC flag or only actually register participating players? For reference, I keep the global config.yml stat setting disabled - ``stats: false``.

**Comment by Eredrim** [comment]
Fixed.
