### ISSUE TITLE
Inventory loss due to BattlefieldGuard module when entering region from outside.

### ISSUE THREAD

**Issue by mibby** [Eredrim/pvparena#48]
PVPArena dev 336
Modules as of dev 209

@Eredrim I managed to find a reproductive step leading to loss of inventory / wiping / cloning!

> If a non-admin player get's out of the lounge without tp, and then climbs up any of the island arenas. When half-way up climbing, the player gets automatically kicked out of the duel arena and is then teleported to /spawn for a split second. After that split second, the player is then teleported back to the original area the player was before joining /duel . Their whole inventory is wiped and replaced with the arena kit.

> When entering.
> In the lounge -> walk into a map’s battlefield region -> kicked to spawn -> tped back to lounge -> leave using /pa leave = inventory glitch

More specifically;

![link](https://i.imgur.com/1v8ILcp.png)

It happens when players somehow manage to leave the lounge and try to "enter" from outside into a region / arena that is protected with BattlefieldGuard. I'm unsure if they were trying to enter the _same_ arena they were in the lounge for or just any existing in the area (but part of same shortcut rotation) -- or if that even matters. But they were trying to enter from outside while in a readying state. 

This might also happen if you try to _leave_ a battlefieldguard region when readying or in battle state -- still testing though.

**Comment by mibby** [comment]
Here's a follow-up test.

![link2](https://i.imgur.com/1UzPVfb.png)

**Comment by Eredrim** [comment]
Fixed !
However a few precisions are needed. BattlefieldGuard only protects from player entrance in regions of other arenas or if players is not inside an arena. These are arena regions themselves which are in charge of kicking players who go out.
In any case, there was a bug both on module and on region manager so you've been right to precise it 😄 

Don't hesitate to reopen the issue if you continue to experience problem.
