### ISSUE TITLE
FlySpectate not allowing flight

### ISSUE THREAD

**Issue by JohnSF93** [Eredrim/pvparena#49]
Paper version git-Paper-350 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)
PVP version - 1.15.0-SNAPSHOT-b336
FlySpectate - 1.15.0-SNAPSHOT 

As a default player or as admin with full permissions, when accessing spectate through /pa [arena] spectate, the hotbar changes to creative, you are invisible to players in the arena, but unable to fly; double tapping space has no effect.

**Comment by Eredrim** [comment]
Fixed ! :)
You can try it with latest dev build of modules pack: https://ci.craftyn.com/job/PVP%20Arena%20Modules/

**Comment by JohnSF93** [comment]
Thanks, this works when downloading the flySpectate.jar manually, however I believe that this updated .jar is not included in the .zip filepack. It's the same size as the old one and doesn't work when downloaded from there. Many thanks!

**Comment by Eredrim** [comment]
Thanks to highlighted it, there was an error in my jenkins config. I fixed it.
