### ISSUE TITLE
Unable to join an arena on a specific team anymore.

### ISSUE THREAD

**Issue by mibby** [Eredrim/pvparena#50]
PVPArena dev 340

Players are unable to join an arena on a specific time anymore with the command ``/pa <arena> <team>``. Such as ``/pa ctf red`` when joining from outside. If this is intended, could you perhaps add a command to switch teams from within the lobby?

Broke in commit https://github.com/Eredrim/pvparena/commit/e5c0e58e4c2af31c1f880de08a912ff4a1474213 ?

**Comment by Eredrim** [comment]
Hi,

Command `/pa <arena> <team>` never allowed to join a specific team, it just joining an arena without team consideration. I fixed an issue which redirected any incorrect command starting with `/pa <arena> <anything else>` to `/pa <arena>`. Now if you want to join a specific team, just use the dedicated command (that didn't change :smile: ) `/pa <arena> join <team>` or `/pa <arena> -j <team>`.

**Comment by mibby** [comment]
I see, thanks! I never knew about the join command, always used joining without team consideration by specifying a team in the join command. :)
