### ISSUE TITLE
Infected team set does not set scoreboard color.

### ISSUE THREAD

**Issue by mibby** [Eredrim/pvparena#52]
PVPArena dev 341
Modules dev 213

I created a concept BlockHunt minigame using the INFECT goal. Infected team color does not seem to set the infected player's color properly on the scoreboard. 

I tried both

```
teams:
  free: LIGHT_BLUE
  infected: RED
```

&

```
teams:
  free: LIGHT_BLUE
  '%infected%': RED
```

Regardless of what is set, the infected team is colored white.

Config Example
https://paste.ubuntu.com/p/XbRyN3NPxG/

Edit: Specifically the scoreboard on the right here. Though the screenshot is of a player who was visually stuck dying.
![link](https://i.imgur.com/SUzRA4S.png)

**Comment by Eredrim** [comment]
Fixed

**Comment by mibby** [comment]
@Eredrim Every time a non-infected dies to become infected, they remain blue. Basically scoreboard isn't updating on team change.

![link2](https://cdn.discordapp.com/attachments/144136525553205248/736286816352600144/unknown.png)
