### ISSUE TITLE
BetterClasses module - respawnCommand runs twice and runs on initial spawn into the arena.

### ISSUE THREAD

**Issue by mibby** [Eredrim/pvparena#54]
PVPArena dev 341
Modules dev 213
Paper dev 101 (Spigot 1.16.1)
LibsDisguises dev 674

Arena Config - BlockHunt
https://paste.ubuntu.com/p/FYMh7TrnGm/

The BetterFight respawnCommand setting seems to run twice when it occurs and also runs on initial spawn into the arena.

1) Can the respawnCommand only run once?

2) Can it only run for actual respawns and not _any_ spawns, i.e. initial spawning into the arena on game start?

---

Per my server logs;

Was an initial infected.
> [19:39:44] [Server thread/INFO]: Gurrecool not disguised!
[19:39:44] [Server thread/INFO]: Gurrecool not disguised!

Was an initial survivor who got infected.
> [19:39:59] [Server thread/INFO]: TheFinalSnow is no longer disguised
[19:39:59] [Server thread/INFO]: TheFinalSnow not disguised!

Was an initial infected.
> [19:45:45] [Server thread/INFO]: PoopSecret not disguised!
[19:45:45] [Server thread/INFO]: PoopSecret not disguised!

Was an initial survivor who got infected.
> [19:46:04] [Server thread/INFO]: brynhill is no longer disguised
[19:46:04] [Server thread/INFO]: brynhill not disguised!

Was an initial infected.
> [20:07:26] [Server thread/INFO]: TheFinalSnow not disguised!
[20:07:26] [Server thread/INFO]: TheFinalSnow not disguised!

Was an initial infected.
> [20:09:14] [Server thread/INFO]: Beary325 not disguised!
[20:09:14] [Server thread/INFO]: Beary325 not disguised!

Was an initial survivor who got infected.
> [20:21:56] [Server thread/INFO]: brynhill is no longer disguised
[20:21:56] [Server thread/INFO]: brynhill not disguised!

**Comment by Eredrim** [comment]
This issue affects BetterClasses and not BetterFight (which has no respawnCommand feature). Everything has been fixed in 2.0.
