### ISSUE TITLE
Question - Are players kicked out of the arena first before teleporting to old location on restore?

### ISSUE THREAD

**Issue by mibby** [Eredrim/pvparena#55]
PVPArena dev 341
Modules dev 213
Paper dev 101 (Spigot 1.16.1)

Arena Config - BlockHunt
https://paste.ubuntu.com/p/FYMh7TrnGm/

I've been getting some reports from players that they are brought to my spawn location on game end, and only then after are brough back to their ``old`` joining location.

```
tp:
  death: old
  exit: old
  lose: old
  win: old
```

My spawn _is_ set as an exit location, but all tp is configured to teleport to old on end.

```
spawns:
  exit: spawn,9,58,0,-269.92340087890625,13.349924087524414
```

The BattlefieldGuard module _is_ enabled, which leads me to believe that it is protecting the arena and teleporting players _out_ due to being inside the region on game end. Thus leads to the question -- are players kicked out of the arena playing state before they are restored and teleported to old?

**Comment by JohnStar128** [comment]
I've noticed a similar behavior in my time using PVPAreana, mostly with the 1.11 version, on a 1.12.2 server.

Take for example a Spleef arena, when a player is taken out of the BATTLE region, they are sent back to their `old` location, but the arena still treats them as a player in the arena. When the game finally ends, it teleports everyone to the appropriate exit/end/win/lose locations, including those people who already lost. This behavior has been seen in other free/tdm modes as well. I haven't been sure of this being an issue of my not configuring it properly, or just an odd behavior of the plugin.

I just set up a test server running 1.14.0 on the latest Paper (paper-131) in 1.16 (so far everything seems to work pretty well) and the same issue persists. Would love some clarification if anyone's more familiar with this situation.

**Comment by Eredrim** [comment]
I tried to reproduce it during one hour but I didn't succeed. In FFA or in teams gamemode, when a player goes out of the BATTLE region, he was fully kicked of the arena. At the end of game, he's not teleported again to another place.
Concerning Battlefieldguard, it protects from entering in area regions for external players. So there's no link with observed behavior (I took the time to make a try to be sure).

So if one of you can reproduce it, I would be interested by its configuration and by the way to recreate the issue step by step.
