### ISSUE TITLE
BetterFight module - Option to add knockback registering events when throwing snowballs / eggs.

### ISSUE THREAD

**Issue by mibby** [Eredrim/pvparena#56]
Once upon a time, there was a bukkit bug that had snowballs and eggs thrown at players cause pvp knockback. This was never originally part of vanilla minecraft but this bug existed long enough that people always assumed it was part of it -- until bukkit finally fixed it. This bug was used in games such as Spleef to prevent corner camping by allowing snowballs to be thrown at players to knock them backwards, off the platform.

The plugin OldCombatMechanics tries to re-implement this bug as a legacy combat option. However I personally do not use legacy mechanics and at this point of time, try to embrace current version combat.
https://github.com/kernitus/BukkitOldCombatMechanics

https://github.com/kernitus/BukkitOldCombatMechanics/blob/10a790a3cfd2cdc38b40ee6dddeaf235647df87b/src/main/java/kernitus/plugin/OldCombatMechanics/module/ModuleProjectileKnockback.java

They also tried re-implementing fishing rod knockback that was used in very old server games as well. For reference;
https://github.com/kernitus/BukkitOldCombatMechanics/blob/10a790a3cfd2cdc38b40ee6dddeaf235647df87b/src/main/java/kernitus/plugin/OldCombatMechanics/module/ModuleFishingKnockback.java

**Would it be possible for the BetterFight module to get an option to listen for snowball/egg pvp interact events and throw a damage event to cause knockback _only_ while players are inside the arena (such as spleef)?**

**Comment by Eredrim** [comment]
The objective of betterfight is to get one-shot items. I don't understand the interest while adding knockback.

**Comment by mibby** [comment]
I misunderstood BetterFight as a module for enhancing fighting mechanics outside the scope of vanilla, i.e. exploding on death or one-hit items. Since it already has support for registering one-hit items like snowballs, I figured expanding it to allow an option for knockback instead of one-hit would be within the same scope of the module. 

The only real purpose of adding knockback as far as I can come up with is for the Spleef gamemode to prevent corner camping.

**Comment by Eredrim** [comment]
I created a new module named "Projectiles" that adds knockback for snowballs, eggs and even fish hooks and ender pearls. Download the latest dev build of both PVPArena and PVPArena_modules if you want to try it.
