### ISSUE TITLE
Blocks removed with BlockDissolve module aren't restored post-game

### ISSUE THREAD

**Issue by JohnStar128** [Eredrim/pvparena#58]
**PVPArena**: 1.15.0-SNAPSHOT-b342, 1.14.0
**BlockDissolve:** 1.14.0
**BlockRestore**: 1.14.0
**Server**: git-Paper-"9788250b1" (paper-131, 1.16.1), git-Paper-243 (1.14.4)

**Expected behavior**: Blocks broken by the BlockDestroy module being restored on game over.

**Observed behavior**: Only blocks broken by players being restored. Ones broken by standing on them were still broken after the match.

I tried setting BlockRestore's `hard` option to true with no avail as well. A few other behaviors I noticed, on a 1.14.4 server running the latest 1.14.0 release, the blocks did actually restore, but significantly slower than the rate that BlockRestore restores blocks. Attempting the latest 1.14.0 version on a 1.16.1 Paper server did not restore blocks from the BlockDissolve module at all, and setting the `hard` option in BlockRestore to true would crash the server.

**Comment by Eredrim** [comment]
Fixed in build #216
