### ISSUE TITLE
Escaping an arena

### ISSUE THREAD

**Issue by Joseph0430** [Eredrim/pvparena#7]
When i join an arena with no one else there, i get trapped, and even if I tp myself out, I can't break/place blocks. How do I escape the arena after joining when there is nobody else to start the game?

**Comment by Joseph0430** [comment]
Spigot 1.13.2 and #306 build on jenkins

**Comment by Oruss7** [comment]
Hello,
Have you try `/pa leave` ? How do you join your arena ? `/pa <arena> join ` ?
