### ISSUE TITLE
[Suggestion] Placeholder for PvpArena

### ISSUE THREAD

**Issue by tiradorus** [Eredrim/pvparena#80]
Everything is in the title =)
Add us some placeholders into PvpArena ^^ I use Skript and MyCommand to create some unique events, and i can't use PvpArenas things into thoses plugins.

Even the module 'EventActions' is a stand-alone module, that interact only with PvPArena :S

So ... if you can add the placeholders of this module ... as PvpArena "global" placeholder, it could be great =)

Have a nice day!

**Comment by Eredrim** [comment]
Implemented in 2.0 dev preview
