### ISSUE TITLE
Respawn issues for Geyser/Bedrock clients

### ISSUE THREAD

**Issue by Gryzvwald** [Eredrim/pvparena#92]
**Issue:**
Geyser/Bedrock clients do not see a respawned Java client inside of an arena properly. Does not matter if it was a Bedrock client that killed a Java client player or a Java client player that killed another Java client player. To the Bedrock/Geyser client the killed Java client player doesn't appear to respawn and is lying on the ground and can not be targeted.

The problem persists outside of the arena until either the Bedrock/Geyser player dies and respawns or the Java player that is invulnerable dies and respawns. 

**Version Info:**
- Server jar's tested: Paper 1.16.1 to 1.16.5
- Client versions: Java 1.16.5, Bedrock v1.16.210
- floodgate-bukkit.jar (latest build 4)
- Geyser-Spigot.jar (latest build 650)
- pvparena-1.15.1.jar
- worldedit-bukkit-7.2.4.jar
- worldguard-bukkit-7.0.4.jar

![BedrockClientPoV_JavaClientKillingJavaClient](https://user-images.githubusercontent.com/17738447/111823953-ce2bf980-88a2-11eb-9d1c-33fc3cc25feb.png)
![BedrockClientPoV_KillingJavaClient](https://user-images.githubusercontent.com/17738447/111823926-c704eb80-88a2-11eb-904d-7b974e4acd0f.png)

**Comment by Gryzvwald** [comment]
I should add that this issue only happens within an arena. Bedrock players that kill Java players in normal PvP do not see any respawn issues.

**Comment by Eredrim** [comment]
Hi,

For me it really too specific to be fixed in priority. GeyserMC is currently in development stage (pre-alpha) and this bug only appears with Bedrock players. 

In next PVP Arena major version (2.0 - currently in development), it's planned to change death system. So it might be fixed at this moment.

**Comment by Gryzvwald** [comment]
Thank you Eredrim. I just wanted to document it and make the team aware. In case anyone else runs into this issue.

**Comment by Eredrim** [comment]
Fixed in 2.0 dev preview
